version: '3.9'
services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
    web: &app_base
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - .:/myapp
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: development
        depends_on:
            - db
    webpack:
        <<: *app_base
        command: 'yarn start'
        ports:
            - '8080:8080'
        depends_on:
            - web
        tty: false
        stdin_open: false
        environment:
            NODE_ENV: development

